name: tagged-release
on:
    push:
        tags:
            - "v*"
jobs:
    release:
        name: "Release"
        runs-on: ubuntu-latest
        steps:
            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: ${{ secrets.RELEASE_TOKEN }}
                prerelease: false
            - name: "add-tags"
              run: |
                IFS=',' read -ra TAGS <<< "${GITHUB_REF#refs/tags/}"
                for tag in "${TAGS[@]}"; do
                git tag -a "$tag" -m "$tag"
                done
                shell: bash
            - name: "push-tags"
              run: git push origin --tags
              shell: bash
